name: Docker

on:
  workflow_dispatch: {}
  # schedule:
  #   - cron: "0 16 * * 1"
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - entrypoint.sh
  pull_request:
    paths:
      - Dockerfile

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker_aws_cli:
    name: docker build
    uses: Docker-Collection/reusable-workflows/.github/workflows/docker-build.yml@main
    with:
      docker_name: "ghcr.io/docker-collection/packsquash-egg"
      docker_label_author: "Efina"
      docker_label_title: "PackSquash but Pterodactyl!"
      docker_label_description: "For Pterodactyl egg"
      version_detecter: true
      version_detecter_file: "Dockerfile"
      version_detecter_var: "PACKSQUASH_VERSION="
